# Generated by Django 5.0.6 on 2024-05-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_value', models.CharField(max_length=20, verbose_name='Ціна')),
                ('pc_description', models.CharField(max_length=200, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Ціна',
                'verbose_name_plural': 'Ціни',
            },
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_title', models.CharField(default='-', max_length=200, null=True, verbose_name='Послуга')),
                ('pt_old_price', models.CharField(default='-', max_length=200, null=True, verbose_name='Стара ціна')),
                ('pt_new_price', models.CharField(default='-', max_length=200, null=True, verbose_name='Нова ціна')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
            },
        ),
    ]
